backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: assets/images
public_folder: images

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true

    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime',  date_format: "YYYY-MM-DDTHH:mm:ssZ", format: "YYYY-MM-DDTHH:mm:ssZ", picker_utc: true }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' } 
      - { label: 'Categories', name: 'categories', widget: 'list' }
      - { label: 'Image', name: 'image', widget: 'image' } 
      - { label: 'Body', name: 'body', widget: 'markdown' }

