const defaultTheme = require('tailwindcss/defaultTheme');
const colors = require('tailwindcss/colors');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'bg-primary': '#0f0f0f',
        'bg-surface': '#181818',
        'text-primary': '#fafafa',
        'text-muted': '#a1a1aa',
        accent: colors.indigo[600],
      },
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
        serif: ['Lora', ...defaultTheme.fontFamily.serif],
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.gray.600'),
            '--tw-prose-headings': theme('colors.gray.900'),
            '--tw-prose-links': theme('colors.indigo.600'),
            '--tw-prose-bold': theme('colors.gray.900'),
            '--tw-prose-quotes': theme('colors.gray.900'),
            '--tw-prose-quote-borders': theme('colors.indigo.500'),
            fontSize: '1.125rem',
            lineHeight: '1.75',
            h1: { 
              fontFamily: theme('fontFamily.serif').join(', '),
              fontSize: '2.5rem',
              lineHeight: '1.2',
              fontWeight: '600',
              letterSpacing: '-0.02em',
              marginTop: '0',
              marginBottom: '1.5rem',
              color: theme('colors.gray.900'),
            },
            h2: { 
              fontFamily: theme('fontFamily.serif').join(', '),
              fontSize: '1.875rem',
              lineHeight: '1.3',
              fontWeight: '600',
              marginTop: '2.5rem',
              marginBottom: '1rem',
              color: theme('colors.gray.900'),
            },
            h3: { 
              fontFamily: theme('fontFamily.serif').join(', '),
              fontSize: '1.5rem',
              lineHeight: '1.4',
              fontWeight: '600',
              marginTop: '2rem',
              marginBottom: '0.75rem',
              color: theme('colors.gray.900'),
            },
            h4: { 
              fontFamily: theme('fontFamily.serif').join(', '),
              fontSize: '1.25rem',
              lineHeight: '1.5',
              fontWeight: '600',
              marginTop: '1.5rem',
              marginBottom: '0.5rem',
              color: theme('colors.gray.900'),
            },
            p: {
              marginTop: '1.25rem',
              marginBottom: '1.25rem',
              lineHeight: '1.75',
            },
            'ul, ol': {
              marginTop: '1.25rem',
              marginBottom: '1.25rem',
            },
            li: {
              marginTop: '0.5rem',
              marginBottom: '0.5rem',
            },
            blockquote: {
              fontStyle: 'normal',
              borderLeftWidth: '4px',
              borderLeftColor: theme('colors.gray.300'),
              paddingLeft: '1.5rem',
              marginTop: '2rem',
              marginBottom: '2rem',
              backgroundColor: theme('colors.gray.50'),
              padding: '1.5rem',
              borderRadius: '0.5rem',
            },
          },
        },
        invert: { // This is the dark mode configuration
          css: {
            '--tw-prose-body': theme('colors.slate.300'),
            '--tw-prose-headings': theme('colors.white'),
            '--tw-prose-links': theme('colors.slate.200'),
            '--tw-prose-bold': theme('colors.white'),
            '--tw-prose-quotes': theme('colors.white'),
            '--tw-prose-quote-borders': theme('colors.slate.600'),
            fontSize: '1.125rem',
            lineHeight: '1.75',
            a: {
              transition: 'color 0.2s ease-in-out',
              '&:hover': {
                color: theme('colors.white'),
              },
            },
            h1: { 
              fontFamily: theme('fontFamily.serif').join(', '),
              fontSize: '2.5rem',
              lineHeight: '1.2',
              fontWeight: '600',
              letterSpacing: '-0.02em',
              marginTop: '0',
              marginBottom: '1.5rem',
              color: theme('colors.slate.100'),
              backgroundImage: 'linear-gradient(135deg, #F8FAFC 0%, #E2E8F0 100%)',
              '-webkit-background-clip': 'text',
              '-webkit-text-fill-color': 'transparent',
              backgroundClip: 'text',
            },
            h2: { 
              fontFamily: theme('fontFamily.serif').join(', '),
              fontSize: '1.875rem',
              lineHeight: '1.3',
              fontWeight: '600',
              marginTop: '2.5rem',
              marginBottom: '1rem',
              color: theme('colors.white'),
            },
            h3: { 
              fontFamily: theme('fontFamily.serif').join(', '),
              fontSize: '1.5rem',
              lineHeight: '1.4',
              fontWeight: '600',
              marginTop: '2rem',
              marginBottom: '0.75rem',
              color: theme('colors.white'),
            },
            h4: { 
              fontFamily: theme('fontFamily.serif').join(', '),
              fontSize: '1.25rem',
              lineHeight: '1.5',
              fontWeight: '600',
              marginTop: '1.5rem',
              marginBottom: '0.5rem',
              color: theme('colors.white'),
            },
            p: {
              marginTop: '1.25rem',
              marginBottom: '1.25rem',
              lineHeight: '1.75',
            },
            'ul, ol': {
              marginTop: '1.25rem',
              marginBottom: '1.25rem',
            },
            li: {
              marginTop: '0.5rem',
              marginBottom: '0.5rem',
            },
            blockquote: {
              fontStyle: 'normal',
              borderLeftWidth: '4px',
              borderLeftColor: theme('colors.slate.500'),
              paddingLeft: '1.5rem',
              marginTop: '2rem',
              marginBottom: '2rem',
              backgroundColor: theme('colors.slate.800'),
              padding: '1.5rem',
              borderRadius: '0.5rem',
            },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography'), require('@tailwindcss/line-clamp')],
}; 