import React from "react";
import Header from "../components/landing/Header";
import Hero from "../components/landing/Hero";
import HowItWorks from "../components/landing/HowItWorks";
import HeadMeta from "../components/HeadMeta";
import SeoAudit from "../components/landing/SeoAudit";
import Footer from "../components/landing/Footer";
import Testimonials from "../components/landing/Testimonials";
import Faq from "../components/landing/Faq";
import TrafficGrowthSection from "../components/landing/TrafficGrowthSection";
import PricingSection from "../components/landing/PricingSection";
import HowAIWorksSection from "../components/landing/HowAIWorksSection";
import WhoIsItForSection from "../components/landing/WhoIsItForSection";
import ComparisonSection from "../components/landing/ComparisonSection";
import MultimediaSection from "../components/landing/MultimediaSection";
import SpeedSection from "../components/landing/SpeedSection";
import GlobalReachSection from "../components/landing/GlobalReachSection";
import BrandVoiceSection from "../components/landing/BrandVoiceSection";
import FeaturesSection from "../components/landing/FeaturesSection";
import CtaSection from "../components/landing/CtaSection";
import WorkflowComparisonSection from "../components/landing/WorkflowComparisonSection";
import TrustedBy from "../components/landing/TrustedBy";


const LandingPage = () => {
  return (
    <div className="bg-white dark:bg-gray-900">
      <HeadMeta
        title="AI-Powered SEO Content That Ranks"
        description="Outrank your competitors with SEO-optimized content generated by AI. Get started for free and watch your organic traffic grow."
        url="https://outblogai.com"
        imageUrl="/path/to/your/image.jpg"
      />
      <Header />
      <main>
      <Hero />
      <TrustedBy />

      <HowItWorks />
      <WhoIsItForSection />

      <HowAIWorksSection />
      
      <TrafficGrowthSection />

      <MultimediaSection />

      <BrandVoiceSection />

      <SpeedSection />

      <FeaturesSection />

      <ComparisonSection />

      <CtaSection />

      <GlobalReachSection />

      <PricingSection />

      <Faq />
      
      <Testimonials />

      <SeoAudit /> 
      </main>
      <Footer />
    </div>
  );
};

export default LandingPage;
