import React from 'react';
import Accordion from './Accordion';

const Faq = () => {
  const faqs = [
    {
      question: "What exactly is OutBlogs?",
      answer: "OutBlogs is an AI-powered content automation platform designed to put your blog on autopilot. We do more than just write text; we handle the entire content lifecycle, from in-depth keyword research and competitor analysis to generating SEO-optimized, long-form articles and even publishing them directly to your website. It's an end-to-end solution for businesses that want to use content marketing to drive traffic without the massive time and cost investment."
    },
    {
      question: "How does the AI work? Is this just another GPT wrapper?",
      answer: "No, OutBlogs is far more advanced than a simple GPT wrapper. Our platform uses a proprietary multi-stage AI process. It starts by analyzing SERPs (Search Engine Results Pages) for your target keywords to understand search intent. Then, it outlines an article structure based on top-ranking content. Finally, our 'Advanced AI' model, which is fine-tuned for high-quality, long-form content, generates an article that is not only original and readable but also strategically designed to rank."
    },
    {
        question: "Is the content truly original and safe from plagiarism?",
        answer: "Yes, 100%. The content generated by OutBlogs is created from scratch by our AI models. It is not scraped, spun, or rephrased from existing articles. Every piece is unique and will pass all standard plagiarism checks like Copyscape. We built our system with content integrity as a top priority, ensuring the articles are genuinely original assets for your brand."
    },
    {
      question: "Can I edit the articles before they are published?",
      answer: "Absolutely. You have complete editorial control. While our AI produces ready-to-publish articles, we understand you may want to add your own brand voice, include specific anecdotes, or tweak certain sections. You can review and edit every article within the OutBlogs dashboard before it goes live on your site."
    },
    {
      question: "What kind of SEO results can I realistically expect?",
      answer: "While we cannot guarantee specific rankings (no honest SEO tool can), our system is designed to maximize your potential for organic traffic growth. By consistently publishing content based on our strategic 30-day plan, which targets relevant, low-competition keywords, users typically start to see a significant uptick in impressions and clicks within 60-90 days. The key is consistency, which OutBlogs makes effortless."
    },
    {
      question: "What integrations do you support?",
      answer: "Instead of relying on clunky integrations, we provide an all-in-one solution. Every OutBlogs plan includes hosting on our specialized, high-performance infrastructure. In simple terms, your blog will be lightning-fast, which is a major factor Google uses for ranking. This means you get a built-in SEO advantage from day one. We also support over 100+ languages for content generation, and are constantly rolling out new features like automatic YouTube video embedding and AI-powered audio versions of your articles."
    }
  ];

  return (
    <section className="py-24 bg-white dark:bg-gray-900">
      <div className="container mx-auto px-8">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">Frequently Asked Questions</h2>
          <p className="text-lg text-gray-600 dark:text-gray-300 mb-12">
            Have questions? We have answers. If you can't find what you're looking for, feel free to contact us.
          </p>
        </div>
        <div className="max-w-3xl mx-auto">
          {faqs.map((faq, index) => (
            <Accordion key={index} title={faq.question}>
              {faq.answer}
            </Accordion>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Faq; 